name: CI

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write # for softprops/action-gh-release to create GitHub release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: Install modules
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
      - name: Build artifact
        run: pnpm build-artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: web-ext-artifacts/extension.zip
